#!/usr/bin/env bash
set -ex -o pipefail

BUF="$(command -v ./node_modules/@bufbuild/buf/bin/buf)" || {
  echo "buf not found... Please install Buf (buf.build)."
  exit 1
}

TIRO_SPEECH_CORE_COMMIT=${TIRO_SPEECH_CORE_COMMIT:-3d403e5}
TIRO_SPEECH_CORE_REPO=${TIRO_SPEECH_CORE_REPO:-"https://github.com/tiro-is/tiro-speech-core.git#ref=${TIRO_SPEECH_CORE_COMMIT},subdir=proto"}

SDIFI_PROTOS_COMMIT=${SDIFI_PROTOS_COMMIT:-611a09a}
SDIFI_PROTOS_REPO=${SDIFI_PROTOS_REPO:-"https://github.com/sdifi/protos.git#ref=${SDIFI_PROTOS_COMMIT}"}

"$BUF" generate "${TIRO_SPEECH_CORE_REPO}"
"$BUF" generate "${SDIFI_PROTOS_REPO}" --include-imports
